### ISSUE TITLE
Gem ruby-serialport not listed as dependency.

### ISSUE THREAD

**Issue by craysiii** [michaelfranzl/ruby-escper#3]
Someone came into freenode#ruby asking for help with your library. Their issue came down to not having the ruby-serialport gem installed, and no where in the README or Gemfile is it listed as a dependency.

**Comment by michaelfranzl** [comment]
The `Gemfile` includes the file `escper.gemspec`, and there, `serialport` is required. For this reason, even rubygems.org lists the dependency, see https://rubygems.org/gems/escper . Executing `gem install escper` will install the `serialport` dependency automatically.

When cloning this git repository for development and loading it manually, this is an advanced use case, and users should know about how to use `bundler`. In this case, always execute `bundle install` before using it. So, the problem lies in the setup and/or knowledge of the user.

**Comment by craysiii** [comment]
This is interesting. From what I understand, the user used gem install escper to install it, but serialport was still not installed. Maybe there is something they didn't tell me.

 I can't believe I missed the gemspec file. I am still new to ruby so apologies.
